### PR TITLE
Allocate embedded pointers on C heap

### LINKED ISSUE #15: Issues with Go 1.6 cgo pointer rules
Go 1.6 is [changing its rules][cgo] around passing Go-owned pointers to C. In particular, you may no longer pass Go pointers which contain Go pointers to C. This obviously poses a serious problem for e.g., `cMechanismList` and `cAttributeList` and other internal abstractions, where ~all the memory in a deeply-nested data structure is owned by Go.

Are there any plans to fix this package to comply with Go 1.6's pointer ownership rules?

[cgo]: https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md

### PR DESCRIPTION
**Pull request by zenazn**
This commit changes cAttributeList and cMechanismList to allocate shadow
copies of each CK_ATTRIBUTE and CK_MECHANISM on the C heap instead of
referencing byte slices on the Go heap. This is in response to upcoming
changes in the Go 1.6 cgo contract, when it becomes illegal to pass a Go
pointer containing other Go pointers to cgo.

(As a note, I haven't been able to get tests to work locally as I have `softhsm2` installed instead of `softhsm`; it's probably worth making sure tests pass before merging this)

This fixes #15

### CODE REVIEW

**Comment by miekg** [comment]
doesn't seem to invasive. Let me beef up testing at bit.

**Comment by miekg** [comment]
Hmmm, running go test -v just trashed my linux laptop

**Comment by miekg** [comment]
I've setup a travis build: https://travis-ci.org/miekg/pkcs11/
This passes the current tests, but I want to expand them (and enable the parallel test again).

For some weird reason my laptop trashes when I run the tests. The current tests should be adaptable to libsofthsm2 fairly easy.

**Comment by miekg** [comment]
So the (few) tests there are actually work: https://travis-ci.org/miekg/pkcs11/builds/98153199

**Comment by miekg** [comment]
can you rebase on master, so I can merge?

**Comment by jsha** [comment]
FYI, we (Boulder team) also had a crash when running softhsm on one of our laptops. The problem appear to be that SoftHSM's RNG initializes entropy by reading files from /proc/. One of those files was related to a WiFi driver, and reading from it caused a kernel panic. We worked around by removing the o+r bit on it: https://github.com/letsencrypt/boulder/blob/master/test/make-softhsm.sh#L8-L14.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [pkcs11] Allocate embedded poin..." ]
>FYI, we (Boulder team) also had a crash when running softhsm on one of our laptops. The problem appear to be that SoftHSM's RNG initializes entropy by reading files from /proc/. One of those files was related to a WiFi driver, and reading from it caused a kernel panic. We worked around by removing the o+r bit on it: https://github.com/letsencrypt/boulder/blob/master/test/make-softhsm.sh#L8-L14.

Aahhh, it *that* what it is. Thanks!


/Miek

--
Miek Gieben

**Pull request merged**
