### PR TITLE
fix SHA HMAC Constants

### PR DESCRIPTION
**Pull request by scottallan**

### CODE REVIEW

**Comment by scottallan** [comment]
used https://www.cryptsoft.com/pkcs11doc/v230/group__SEC__14__MANIFEST__CONSTANTS.html as a reference.

First discovered when testing CKK_SHA256_HMAC with Thales nCipher units and noticed the Type is wrong.

**Comment by miekg** [comment]
Can you provide a little more rational in the description?

**Comment by scottallan** [comment]
when implementing this pkcs11 api and communicating to certain hardware such as Thales nCipher nShield appliances we have noticed that the returned ID for key types of CKK_SHA256_HMAC are hex '2b' or 43 decimal.  In your const file un-modified it is listed as hex 43.
the value from our HSM vendor of hex 43 seems to match https://www.cryptsoft.com/pkcs11doc/v230/group__SEC__14__MANIFEST__CONSTANTS.html
I futher noted that the other SHA HMAC IDs also seem to be wrong.

**Comment by miekg** [comment]
Ack.

 I'm on my mobile so can't check. But these constants came from the pkcs.h
in the repo.

**Comment by scottallan** [comment]
Hmmm.... so it seems to have changed from 2.30 to 2.40
https://www.cryptsoft.com/pkcs11doc/STANDARD/include/v230/pkcs11t.h shows:
#define CKK_SHA256_HMAC     0x0000002B
#define CKK_SHA384_HMAC     0x0000002C
#define CKK_SHA512_HMAC     0x0000002D
#define CKK_SHA224_HMAC     0x0000002E
while https://www.cryptsoft.com/pkcs11doc/STANDARD/include/v240/pkcs11t.h shows:
#define CKK_SHA_1_HMAC          0x00000040UL
#define CKK_SHA224_HMAC         0x00000041UL
#define CKK_SHA256_HMAC         0x00000042UL
#define CKK_SHA384_HMAC         0x00000043UL
#define CKK_SHA512_HMAC         0x00000044UL

Thats annoying ;)

**Comment by miekg** [comment]
WTF. that's pretty stupid indeed....

**Comment by scottallan** [comment]
Ok it seems there was an update to 2.40 for errata:
https://www.oasis-open.org/news/announcements/pkcs-11-v2-40-approved-erratas-published-by-pkcs-11-tc
which links to here http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/pkcs11-base-v2.40-errata01-os.html
and which specifies the updated def files to be here http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/

The pkcs11t.h file here specifies:
#define CKK_SHA256_HMAC         0x0000002BUL
#define CKK_SHA384_HMAC         0x0000002CUL
#define CKK_SHA512_HMAC         0x0000002DUL
#define CKK_SHA224_HMAC         0x0000002EUL

And so I think these are the correct ones.

**Comment by miekg** [comment]
Ok we should probably update that file in the repo as well.

**Comment by gbolo** [comment]
thanks for catching that

**Comment by gbolo** [comment]
@miekg any update on when this can be merged?

**Comment by miekg** [comment]
Ah, totally forgot about this; :LGTM

**Pull request merged**
