### PR TITLE
Adding support for nopkcs11 build flag

### PR DESCRIPTION
**Pull request by smithbk**
This adds support for building with the "-tag nopkcs11" option.
The resulting package will compile successfully without libtool
installed but will fail with an appropriate error message at runtime.

See https://github.com/miekg/pkcs11/issues/46

### CODE REVIEW

**Comment by miekg** [comment]
I expected 1 line change...

Other fixes are welcome as well, but please separate them out in other PRs.

**Comment by smithbk** [comment]
How do you suggest that I separate them out?  I'll be glad to submit a pull request with the one line change if that helps, but what about the rest?  I don't know how to break that up, so suggestions are welcome.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] Adding support f..." ]
>How do you suggest that I separate them out?  I'll be glad to submit a pull request with the one line change if that helps, but what about the rest?  I don't know how to break that up, so suggestions are welcome.

Well, $some git foo? :-)

I don't understand this PR. You just wanted to add a !nopkcs11 build tag?


/Miek

--
Miek Gieben

**Comment by smithbk** [comment]
Yes, initially I thought the !nopkcs11 tag would be sufficient.  While that prevents go from building your pkcs11.go and thus eliminating the missing <ltdl.h> compile error when libtool isn't installed, it just kicks the can down the road and I hit other compile errors.

For example, because I have
     import "github.com/miekg/pkcs11"
     ...
     var ctx pkcs11.Ctx
I now get a compile error saying pkcs11.Ctx is not a type.

So basically, what is in my pull request allows someone to not change any of their code, but to build with "go build -tags nopkcs11" and they end up with no compiler errors even without libtool installed, and at runtime whenever they try to call any of your functions, it results in the error saying that it is not supported and needs to remove the "nopkcs11" tag.

All of the changes to your test allow you to run "go test -tags nopkcs11" and everything passes.

**Comment by miekg** [comment]
Sorry. I'm lost here and I'm inclined not to merge this.

The fix seems to be that if you depend on this package you'll need to install the things it needs to compile.

**Comment by jsha** [comment]
@smithbk, another way to solve this problem would be to create an `optional_pkcs11` package that defines an interface doing the same things `Ctx` does, which either calls out to the real pkcs11 package or a fail-at-runtime version depending on build flags. That could be done without any changes to this package.

FWIW, the cfssl project also has this problem and would benefit from such a package:

https://github.com/cloudflare/cfssl/issues/416
https://github.com/cloudflare/cfssl/issues/563

**Comment by smithbk** [comment]
Thanks @jsha.  Yes, I've worked around in a similar way.  I was trying to be a good open source citizen by contributing something that would prevent others from having to do the same.

**Comment by miekg** [comment]
.... so... ? This PR can be worked into something simpler?

**Comment by jsha** [comment]
I think this change will inevitably be somewhat complicated: Packages that optionally depend on `pkcs11` need to use an interface that can be satisfied either by `pkcs11` itself or by a no-op package. So there will need to be at least one large file that reproduces the functions and constants of `pkcs11`.

But, @smithbk, it looks to me like some of the more invasive changes here are around `check()` and `IsSupported()`, which seem to be included so that tests will pass even when built with the `nopkcs11` tag. I'm guessing this is because other projects may vendor `pkcs11` and run tests with `./...`? I would say that we shouldn't expect `pkcs11` tests to pass with the `nopkcs11` build tag, and projects that vendor `pkcs11` but build with `nopkcs11` shouldn't expect its tests to pass that way. I believe in Go 1.9 the behavior of `go test ./...` has been changed to not include vendored packages, which may make this easier. So I'd recommend reverting the changes in pkcs11_test. Also, there seems to be spurious reindenting in const.go. I'd suggest moving BLD_ERR_MSG into `nopkcs11.go` and restoring const.go to the version in master. I think that will wind up as a much simpler PR.

**Pull request closed without merging**
