### PR TITLE
Expose login API for vendor specific login types

### PR DESCRIPTION
**Pull request by dempfi**
First of all thx for the great library, it's really helped me a lot.

The purpose of this PR is to change a bit the session's login API in order to support custom (vendor specific) user types. 

I'm working ATM with SafeNet's Luna SA module and it has support for richer and stricter user model. In order to be able to use its user model one must provide user type in vendor range (above `0x80000000`), so in order to not pollute the library with vendor-specific detail best option seems to be exposition of login method.

### CODE REVIEW

**Comment by miekg** [comment]
this is not backwards compatible so it will break everybody and I don't see a good reason to do this (it also doesn't compile on travis).

A `LoginUser()` (in maybe a new file `vendor_user.go`), with documentation can make sense.

**Comment by dempfi** [comment]
@miekg, problem is — there are different vendors with different vendor extensions. So support for them is quite unreasonable. However I see your point on breaking changes. What if I add a new function, say `LoginAs/2` and don't change any of the existing methods?

**Comment by dempfi** [comment]
@miekg please take a look — I've updated the PR to reflect my suggestion.

**Comment by miekg** [comment]
Lgtm

**Comment by dempfi** [comment]
Awesome, thank you @miekg 🎉

**Pull request merged**
