### PR TITLE
fix LDFLAGS for darwin to avoid go1.9.4 error

### LINKED ISSUE #63: invalid LDFLAGS break build with go1.9.4 / go1.10rc2
On Linux, I'm getting the following error when trying to build the master version with go1.9.4:
```
$ go install ./...
go build github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -Wl,--no-as-needed
```

On Mac OS, getting the error:
```
$ go install ./...
go build github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool
```

Same errors with go1.10rc2.  This is likely be due to changes / security fixes in https://github.com/golang/go/issues/23672

@miekg

### PR DESCRIPTION
**Pull request by dmitris**
PR fixes #63 for Darwin
@miekg

### CODE REVIEW

**Comment by miekg** [comment]
Can you update all Unixes?

**Comment by dmitris** [comment]
I suggest to start with merging this as is, for the sake of the `Darwin`, and then figure out what to do for Unix (not sure about Windows).

**Comment by justincormack** [comment]
Ah, was just about to open a PR for the same thing!

**Comment by miekg** [comment]
~~~
diff --git a/pkcs11.go b/pkcs11.go
index 7abc9a1..b6fdef3 100644
--- a/pkcs11.go
+++ b/pkcs11.go
@@ -13,7 +13,7 @@ package pkcs11
 /*
 #cgo windows CFLAGS: -DREPACK_STRUCTURES
 #cgo windows LDFLAGS: -Wl,--no-as-needed -lltdl
-#cgo linux LDFLAGS: -Wl,--no-as-needed -lltdl -ldl
+#cgo linux LDFLAGS: -lltdl -ldl
 #cgo darwin CFLAGS: -I/usr/local/share/libtool
 #cgo darwin LDFLAGS: -lltdl -L/usr/local/lib/
 #cgo openbsd CFLAGS: -I/usr/local/include/
~~~
makes it compile on my Linux debian box.

**Comment by justincormack** [comment]
Linux and Windows need fixes too, I can do a PR for those.

**Comment by miekg** [comment]
please do @justincormack

**Comment by ruiadrmartins** [comment]
Just to add, it also happens on go 1.8.7 on Linux at least

**Comment by andlabs** [comment]
I'd personally wait to see if the Go team whitelists `-Wl,-no-as-needed`.

**Pull request merged**
